# Generated by Django 4.0.4 on 2022-05-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateTimeField()),
                ('twitter_handle', models.CharField(max_length=20)),
            ],
        ),
    ]
