# Generated by Django 4.0.4 on 2022-05-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
