# Generated by Django 4.0.4 on 2022-05-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scoreboard', '0002_scoreboard_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scoreboard',
            new_name='Score',
        ),
    ]
