# Generated by Django 4.0.4 on 2022-05-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scoreboard', '0003_rename_scoreboard_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='score_value',
        ),
    ]
