# Generated by Django 4.0.4 on 2022-05-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scoreboard', '0005_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
    ]
