# Generated by Django 4.0.4 on 2022-06-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalId', models.CharField(max_length=50)),
                ('zbdId', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('expiresAt', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('lnAddress', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.IntegerField()),
                ('score_date', models.DateTimeField()),
                ('twitter_handle', models.CharField(max_length=50)),
                ('bolt11_invoice', models.CharField(max_length=300)),
            ],
        ),
    ]
