# Generated by Django 4.0.4 on 2022-06-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satsmanscoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
