# Generated by Django 4.0.4 on 2022-06-22 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('satsmanscoreboard', '0002_alter_score_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
