# Generated by Django 4.0.4 on 2022-06-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satsmanscoreboard', '0003_alter_score_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
