# Generated by Django 4.0.4 on 2022-06-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satsmanscoreboard', '0005_delete_invoice_score_expiresat_score_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='status',
            new_name='paid',
        ),
    ]
