# Generated by Django 4.0.4 on 2022-06-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satsmanscoreboard', '0006_rename_status_score_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='expiresAt',
        ),
    ]
