# Generated by Django 4.0.4 on 2022-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satsmanscoreboard', '0007_remove_score_expiresat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
