# Generated by Django 4.0.4 on 2023-05-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satsmanscoreboard', '0009_score_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='npub',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
