# Generated by Django 4.0.4 on 2023-05-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satsmanscoreboard', '0010_score_npub_score_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ln_address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
