# Generated by Django 4.0.4 on 2023-05-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satsmanscoreboard', '0012_score_nip05'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='event',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='ln_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='nip05',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='npub',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='twitter_handle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
