# Generated by Django 4.0.4 on 2023-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satsmanscoreboard', '0013_alter_score_event_alter_score_ln_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='updated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
